name: Advanced Tests (Manual)

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of advanced test to run'
        required: true
        default: 'asr-basic'
        type: choice
        options:
          - asr-basic
          - asr-integration
          - full-suite

jobs:
  advanced-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-mock requests-mock
    
    - name: Run selected tests
      env:
        API_KEY: "test-api-key"
        LOCAL_STORAGE_PATH: "/tmp"
        CI: true
      run: |
        case "${{ github.event.inputs.test_type }}" in
          "asr-basic")
            if [ -f "tests/asr/test_asr_transcribe.py" ]; then
              pytest tests/asr/test_asr_transcribe.py -v --tb=short -m "unit"
            else
              echo "ASR tests not found, skipping"
            fi
            ;;
          "asr-integration")
            if [ -f "tests/asr/test_asr_integration.py" ]; then
              pytest tests/asr/test_asr_integration.py -v --tb=short || echo "Integration tests completed with warnings"
            else
              echo "ASR integration tests not found, skipping"
            fi
            ;;
          "full-suite")
            pytest tests/ -v --tb=short --maxfail=10
            ;;
        esac
