name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          # Smoke tests for PRs
          pytest tests/test_health_endpoint.py tests/test_startup.py -v --tb=short
        else
          # Full tests for main branch
          pytest tests/ -v --tb=short --cov=routes --cov=services --cov=app --cov-report=xml
        fi
      env:
        CI: true
