name: Build Number (Manual)

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Increment build number'
        required: false
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  update-build-number:
    runs-on: ubuntu-latest
    if: github.event.inputs.increment == 'true'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update build number
        run: |
          if [ ! -f build_number.txt ]; then
            echo "1" > build_number.txt
          else
            build_number=$(( $(cat build_number.txt) + 1 ))
            echo $build_number > build_number.txt
          fi
          
          echo "Build number updated to: $(cat build_number.txt)"
      
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add build_number.txt
          git commit -m "Bump build number to $(cat build_number.txt) [skip ci]" || echo "No changes to commit"
          git push || echo "Nothing to push"
